/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/targets` | `/targets`; params?: Router.UnknownInputParams; } | { pathname: `/category/add`; params?: Router.UnknownInputParams; } | { pathname: `/target/add`; params?: Router.UnknownInputParams; } | { pathname: `/application/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/application/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/application/[id]/status`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/category/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/targets` | `/targets`; params?: Router.UnknownOutputParams; } | { pathname: `/category/add`; params?: Router.UnknownOutputParams; } | { pathname: `/target/add`; params?: Router.UnknownOutputParams; } | { pathname: `/application/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/application/[id]/edit`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/application/[id]/status`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/category/[id]/edit`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/insights${`?${string}` | `#${string}` | ''}` | `/insights${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/targets${`?${string}` | `#${string}` | ''}` | `/targets${`?${string}` | `#${string}` | ''}` | `/category/add${`?${string}` | `#${string}` | ''}` | `/target/add${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/targets` | `/targets`; params?: Router.UnknownInputParams; } | { pathname: `/category/add`; params?: Router.UnknownInputParams; } | { pathname: `/target/add`; params?: Router.UnknownInputParams; } | `/application/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/application/${Router.SingleRoutePart<T>}/edit${`?${string}` | `#${string}` | ''}` | `/application/${Router.SingleRoutePart<T>}/status${`?${string}` | `#${string}` | ''}` | `/category/${Router.SingleRoutePart<T>}/edit${`?${string}` | `#${string}` | ''}` | { pathname: `/application/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/application/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/application/[id]/status`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/category/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
